import type {Country} from './countries';
export const ALL_COUNTRIES_FALLBACK: Country[] = [
  {"name":"Aruba","officialName":"","cca2":"AW","flag":"https://flagcdn.com/w640/aw.png"},
  {"name":"Afghanistan","officialName":"Islamic Republic of Afghanistan","cca2":"AF","flag":"https://flagcdn.com/w640/af.png"},
  {"name":"Angola","officialName":"Republic of Angola","cca2":"AO","flag":"https://flagcdn.com/w640/ao.png"},
  {"name":"Anguilla","officialName":"","cca2":"AI","flag":"https://flagcdn.com/w640/ai.png"},
  {"name":"Åland Islands","officialName":"Åland Islands","cca2":"AX","flag":"https://flagcdn.com/w640/ax.png"},
  {"name":"Albania","officialName":"Republic of Albania","cca2":"AL","flag":"https://flagcdn.com/w640/al.png"},
  {"name":"Andorra","officialName":"Principality of Andorra","cca2":"AD","flag":"https://flagcdn.com/w640/ad.png"},
  {"name":"United Arab Emirates","officialName":"United Arab Emirates","cca2":"AE","flag":"https://flagcdn.com/w640/ae.png"},
  {"name":"Argentina","officialName":"Argentine Republic","cca2":"AR","flag":"https://flagcdn.com/w640/ar.png"},
  {"name":"Armenia","officialName":"Republic of Armenia","cca2":"AM","flag":"https://flagcdn.com/w640/am.png"},
  {"name":"American Samoa","officialName":"American Samoa","cca2":"AS","flag":"https://flagcdn.com/w640/as.png"},
  {"name":"Antarctica","officialName":"","cca2":"AQ","flag":"https://flagcdn.com/w640/aq.png"},
  {"name":"French Southern Territories","officialName":"Territory of the French Southern and Antarctic Lands","cca2":"TF","flag":"https://flagcdn.com/w640/tf.png"},
  {"name":"Antigua and Barbuda","officialName":"Antigua and Barbuda","cca2":"AG","flag":"https://flagcdn.com/w640/ag.png"},
  {"name":"Australia","officialName":"Commonwealth of Australia","cca2":"AU","flag":"https://flagcdn.com/w640/au.png"},
  {"name":"Austria","officialName":"Republic of Austria","cca2":"AT","flag":"https://flagcdn.com/w640/at.png"},
  {"name":"Azerbaijan","officialName":"Republic of Azerbaijan","cca2":"AZ","flag":"https://flagcdn.com/w640/az.png"},
  {"name":"Burundi","officialName":"Republic of Burundi","cca2":"BI","flag":"https://flagcdn.com/w640/bi.png"},
  {"name":"Belgium","officialName":"Kingdom of Belgium","cca2":"BE","flag":"https://flagcdn.com/w640/be.png"},
  {"name":"Benin","officialName":"Republic of Benin","cca2":"BJ","flag":"https://flagcdn.com/w640/bj.png"},
  {"name":"Bonaire, Sint Eustatius and Saba","officialName":"Bonaire, Sint Eustatius and Saba","cca2":"BQ","flag":"https://flagcdn.com/w640/bq.png"},
  {"name":"Burkina Faso","officialName":"Burkina Faso","cca2":"BF","flag":"https://flagcdn.com/w640/bf.png"},
  {"name":"Bangladesh","officialName":"People's Republic of Bangladesh","cca2":"BD","flag":"https://flagcdn.com/w640/bd.png"},
  {"name":"Bulgaria","officialName":"Republic of Bulgaria","cca2":"BG","flag":"https://flagcdn.com/w640/bg.png"},
  {"name":"Bahrain","officialName":"Kingdom of Bahrain","cca2":"BH","flag":"https://flagcdn.com/w640/bh.png"},
  {"name":"Bahamas","officialName":"Commonwealth of the Bahamas","cca2":"BS","flag":"https://flagcdn.com/w640/bs.png"},
  {"name":"Bosnia and Herzegovina","officialName":"Bosnia and Herzegovina","cca2":"BA","flag":"https://flagcdn.com/w640/ba.png"},
  {"name":"Saint Barthélemy","officialName":"Collectivity of Saint Barthélemy","cca2":"BL","flag":"https://flagcdn.com/w640/bl.png"},
  {"name":"Belarus","officialName":"Republic of Belarus","cca2":"BY","flag":"https://flagcdn.com/w640/by.png"},
  {"name":"Belize","officialName":"Belize","cca2":"BZ","flag":"https://flagcdn.com/w640/bz.png"},
  {"name":"Bermuda","officialName":"Bermuda","cca2":"BM","flag":"https://flagcdn.com/w640/bm.png"},
  {"name":"Bolivia","officialName":"Plurinational State of Bolivia","cca2":"BO","flag":"https://flagcdn.com/w640/bo.png"},
  {"name":"Brazil","officialName":"Federative Republic of Brazil","cca2":"BR","flag":"https://flagcdn.com/w640/br.png"},
  {"name":"Barbados","officialName":"Barbados","cca2":"BB","flag":"https://flagcdn.com/w640/bb.png"},
  {"name":"Brunei","officialName":"Brunei Darussalam","cca2":"BN","flag":"https://flagcdn.com/w640/bn.png"},
  {"name":"Bhutan","officialName":"Kingdom of Bhutan","cca2":"BT","flag":"https://flagcdn.com/w640/bt.png"},
  {"name":"Bouvet Island","officialName":"Bouvet Island","cca2":"BV","flag":"https://flagcdn.com/w640/bv.png"},
  {"name":"Botswana","officialName":"Republic of Botswana","cca2":"BW","flag":"https://flagcdn.com/w640/bw.png"},
  {"name":"Central African Republic","officialName":"Central African Republic","cca2":"CF","flag":"https://flagcdn.com/w640/cf.png"},
  {"name":"Canada","officialName":"Canada","cca2":"CA","flag":"https://flagcdn.com/w640/ca.png"},
  {"name":"Cocos (Keeling) Islands","officialName":"Territory of the Cocos (Keeling) Islands","cca2":"CC","flag":"https://flagcdn.com/w640/cc.png"},
  {"name":"Switzerland","officialName":"Swiss Confederation","cca2":"CH","flag":"https://flagcdn.com/w640/ch.png"},
  {"name":"Chile","officialName":"Republic of Chile","cca2":"CL","flag":"https://flagcdn.com/w640/cl.png"},
  {"name":"China","officialName":"People's Republic of China","cca2":"CN","flag":"https://flagcdn.com/w640/cn.png"},
  {"name":"Côte d'Ivoire","officialName":"Republic of Côte d'Ivoire","cca2":"CI","flag":"https://flagcdn.com/w640/ci.png"},
  {"name":"Cameroon","officialName":"Republic of Cameroon","cca2":"CM","flag":"https://flagcdn.com/w640/cm.png"},
  {"name":"DR Congo","officialName":"Democratic Republic of the Congo","cca2":"CD","flag":"https://flagcdn.com/w640/cd.png"},
  {"name":"Republic of the Congo","officialName":"Republic of the Congo","cca2":"CG","flag":"https://flagcdn.com/w640/cg.png"},
  {"name":"Cook Islands","officialName":"Cook Islands","cca2":"CK","flag":"https://flagcdn.com/w640/ck.png"},
  {"name":"Colombia","officialName":"Republic of Colombia","cca2":"CO","flag":"https://flagcdn.com/w640/co.png"},
  {"name":"Comoros","officialName":"Union of the Comoros","cca2":"KM","flag":"https://flagcdn.com/w640/km.png"},
  {"name":"Cape Verde","officialName":"Republic of Cabo Verde","cca2":"CV","flag":"https://flagcdn.com/w640/cv.png"},
  {"name":"Costa Rica","officialName":"Republic of Costa Rica","cca2":"CR","flag":"https://flagcdn.com/w640/cr.png"},
  {"name":"Curaçao","officialName":"Country of Curaçao","cca2":"CW","flag":"https://flagcdn.com/w640/cw.png"},
  {"name":"Christmas Island","officialName":"Territory of Christmas Island","cca2":"CX","flag":"https://flagcdn.com/w640/cx.png"},
  {"name":"Cayman Islands","officialName":"Cayman Islands","cca2":"KY","flag":"https://flagcdn.com/w640/ky.png"},
  {"name":"Cyprus","officialName":"Republic of Cyprus","cca2":"CY","flag":"https://flagcdn.com/w640/cy.png"},
  {"name":"Czechia","officialName":"Czech Republic","cca2":"CZ","flag":"https://flagcdn.com/w640/cz.png"},
  {"name":"Germany","officialName":"Federal Republic of Germany","cca2":"DE","flag":"https://flagcdn.com/w640/de.png"},
  {"name":"Djibouti","officialName":"Republic of Djibouti","cca2":"DJ","flag":"https://flagcdn.com/w640/dj.png"},
  {"name":"Dominica","officialName":"Commonwealth of Dominica","cca2":"DM","flag":"https://flagcdn.com/w640/dm.png"},
  {"name":"Denmark","officialName":"Kingdom of Denmark","cca2":"DK","flag":"https://flagcdn.com/w640/dk.png"},
  {"name":"Dominican Republic","officialName":"Dominican Republic","cca2":"DO","flag":"https://flagcdn.com/w640/do.png"},
  {"name":"Algeria","officialName":"People's Democratic Republic of Algeria","cca2":"DZ","flag":"https://flagcdn.com/w640/dz.png"},
  {"name":"Ecuador","officialName":"Republic of Ecuador","cca2":"EC","flag":"https://flagcdn.com/w640/ec.png"},
  {"name":"Egypt","officialName":"Arab Republic of Egypt","cca2":"EG","flag":"https://flagcdn.com/w640/eg.png"},
  {"name":"Eritrea","officialName":"State of Eritrea","cca2":"ER","flag":"https://flagcdn.com/w640/er.png"},
  {"name":"Western Sahara","officialName":"Sahrawi Arab Democratic Republic","cca2":"EH","flag":"https://flagcdn.com/w640/eh.png"},
  {"name":"Spain","officialName":"Kingdom of Spain","cca2":"ES","flag":"https://flagcdn.com/w640/es.png"},
  {"name":"Estonia","officialName":"Republic of Estonia","cca2":"EE","flag":"https://flagcdn.com/w640/ee.png"},
  {"name":"Ethiopia","officialName":"Federal Democratic Republic of Ethiopia","cca2":"ET","flag":"https://flagcdn.com/w640/et.png"},
  {"name":"Finland","officialName":"Republic of Finland","cca2":"FI","flag":"https://flagcdn.com/w640/fi.png"},
  {"name":"Fiji","officialName":"Republic of Fiji","cca2":"FJ","flag":"https://flagcdn.com/w640/fj.png"},
  {"name":"Falkland Islands","officialName":"Falkland Islands","cca2":"FK","flag":"https://flagcdn.com/w640/fk.png"},
  {"name":"France","officialName":"French Republic","cca2":"FR","flag":"https://flagcdn.com/w640/fr.png"},
  {"name":"Faroe Islands","officialName":"Faroe Islands","cca2":"FO","flag":"https://flagcdn.com/w640/fo.png"},
  {"name":"Micronesia","officialName":"Federated States of Micronesia","cca2":"FM","flag":"https://flagcdn.com/w640/fm.png"},
  {"name":"Gabon","officialName":"Gabonese Republic","cca2":"GA","flag":"https://flagcdn.com/w640/ga.png"},
  {"name":"United Kingdom","officialName":"United Kingdom of Great Britain and Northern Ireland","cca2":"GB","flag":"https://flagcdn.com/w640/gb.png"},
  {"name":"Grenada","officialName":"Grenada","cca2":"GD","flag":"https://flagcdn.com/w640/gd.png"},
  {"name":"Georgia","officialName":"Georgia","cca2":"GE","flag":"https://flagcdn.com/w640/ge.png"},
  {"name":"French Guiana","officialName":"French Guiana","cca2":"GF","flag":"https://flagcdn.com/w640/gf.png"},
  {"name":"Guernsey","officialName":"Bailiwick of Guernsey","cca2":"GG","flag":"https://flagcdn.com/w640/gg.png"},
  {"name":"Ghana","officialName":"Republic of Ghana","cca2":"GH","flag":"https://flagcdn.com/w640/gh.png"},
  {"name":"Gibraltar","officialName":"Gibraltar","cca2":"GI","flag":"https://flagcdn.com/w640/gi.png"},
  {"name":"Greenland","officialName":"Greenland","cca2":"GL","flag":"https://flagcdn.com/w640/gl.png"},
  {"name":"Gambia","officialName":"Republic of the Gambia","cca2":"GM","flag":"https://flagcdn.com/w640/gm.png"},
  {"name":"Guinea","officialName":"Republic of Guinea","cca2":"GN","flag":"https://flagcdn.com/w640/gn.png"},
  {"name":"Guadeloupe","officialName":"Guadeloupe","cca2":"GP","flag":"https://flagcdn.com/w640/gp.png"},
  {"name":"Equatorial Guinea","officialName":"Republic of Equatorial Guinea","cca2":"GQ","flag":"https://flagcdn.com/w640/gq.png"},
  {"name":"Greece","officialName":"Hellenic Republic","cca2":"GR","flag":"https://flagcdn.com/w640/gr.png"},
  {"name":"South Georgia and the South Sandwich Islands","officialName":"South Georgia and the South Sandwich Islands","cca2":"GS","flag":"https://flagcdn.com/w640/gs.png"},
  {"name":"Guatemala","officialName":"Republic of Guatemala","cca2":"GT","flag":"https://flagcdn.com/w640/gt.png"},
  {"name":"Guam","officialName":"Guam","cca2":"GU","flag":"https://flagcdn.com/w640/gu.png"},
  {"name":"Guinea-Bissau","officialName":"Republic of Guinea-Bissau","cca2":"GW","flag":"https://flagcdn.com/w640/gw.png"},
  {"name":"Guyana","officialName":"Co-operative Republic of Guyana","cca2":"GY","flag":"https://flagcdn.com/w640/gy.png"},
  {"name":"Hong Kong","officialName":"Hong Kong Special Administrative Region of the People's Republic of China","cca2":"HK","flag":"https://flagcdn.com/w640/hk.png"},
  {"name":"Heard Island and McDonald Islands","officialName":"Heard Island and McDonald Islands","cca2":"HM","flag":"https://flagcdn.com/w640/hm.png"},
  {"name":"Honduras","officialName":"Republic of Honduras","cca2":"HN","flag":"https://flagcdn.com/w640/hn.png"},
  {"name":"Croatia","officialName":"Republic of Croatia","cca2":"HR","flag":"https://flagcdn.com/w640/hr.png"},
  {"name":"Haiti","officialName":"Republic of Haiti","cca2":"HT","flag":"https://flagcdn.com/w640/ht.png"},
  {"name":"Hungary","officialName":"Hungary","cca2":"HU","flag":"https://flagcdn.com/w640/hu.png"},
  {"name":"Indonesia","officialName":"Republic of Indonesia","cca2":"ID","flag":"https://flagcdn.com/w640/id.png"},
  {"name":"Ireland","officialName":"Republic of Ireland","cca2":"IE","flag":"https://flagcdn.com/w640/ie.png"},
  {"name":"Israel","officialName":"State of Israel","cca2":"IL","flag":"https://flagcdn.com/w640/il.png"},
  {"name":"Isle of Man","officialName":"Isle of Man","cca2":"IM","flag":"https://flagcdn.com/w640/im.png"},
  {"name":"India","officialName":"Republic of India","cca2":"IN","flag":"https://flagcdn.com/w640/in.png"},
  {"name":"British Indian Ocean Territory","officialName":"British Indian Ocean Territory","cca2":"IO","flag":"https://flagcdn.com/w640/io.png"},
  {"name":"Iraq","officialName":"Republic of Iraq","cca2":"IQ","flag":"https://flagcdn.com/w640/iq.png"},
  {"name":"Iran","officialName":"Islamic Republic of Iran","cca2":"IR","flag":"https://flagcdn.com/w640/ir.png"},
  {"name":"Iceland","officialName":"Iceland","cca2":"IS","flag":"https://flagcdn.com/w640/is.png"},
  {"name":"Italy","officialName":"Italian Republic","cca2":"IT","flag":"https://flagcdn.com/w640/it.png"},
  {"name":"Jersey","officialName":"Bailiwick of Jersey","cca2":"JE","flag":"https://flagcdn.com/w640/je.png"},
  {"name":"Jamaica","officialName":"Jamaica","cca2":"JM","flag":"https://flagcdn.com/w640/jm.png"},
  {"name":"Jordan","officialName":"Hashemite Kingdom of Jordan","cca2":"JO","flag":"https://flagcdn.com/w640/jo.png"},
  {"name":"Japan","officialName":"Japan","cca2":"JP","flag":"https://flagcdn.com/w640/jp.png"},
  {"name":"Kenya","officialName":"Republic of Kenya","cca2":"KE","flag":"https://flagcdn.com/w640/ke.png"},
  {"name":"Kyrgyzstan","officialName":"Kyrgyz Republic","cca2":"KG","flag":"https://flagcdn.com/w640/kg.png"},
  {"name":"Cambodia","officialName":"Kingdom of Cambodia","cca2":"KH","flag":"https://flagcdn.com/w640/kh.png"},
  {"name":"Kiribati","officialName":"Republic of Kiribati","cca2":"KI","flag":"https://flagcdn.com/w640/ki.png"},
  {"name":"Comoros","officialName":"Union of the Comoros","cca2":"KM","flag":"https://flagcdn.com/w640/km.png"},
  {"name":"Saint Kitts and Nevis","officialName":"Federation of Saint Christopher and Nevis","cca2":"KN","flag":"https://flagcdn.com/w640/kn.png"},
  {"name":"North Korea","officialName":"Democratic People's Republic of Korea","cca2":"KP","flag":"https://flagcdn.com/w640/kp.png"},
  {"name":"South Korea","officialName":"Republic of Korea","cca2":"KR","flag":"https://flagcdn.com/w640/kr.png"},
  {"name":"Kuwait","officialName":"State of Kuwait","cca2":"KW","flag":"https://flagcdn.com/w640/kw.png"},
  {"name":"Cayman Islands","officialName":"Cayman Islands","cca2":"KY","flag":"https://flagcdn.com/w640/ky.png"},
  {"name":"Kazakhstan","officialName":"Republic of Kazakhstan","cca2":"KZ","flag":"https://flagcdn.com/w640/kz.png"},
  {"name":"Laos","officialName":"Lao People's Democratic Republic","cca2":"LA","flag":"https://flagcdn.com/w640/la.png"},
  {"name":"Lebanon","officialName":"Lebanese Republic","cca2":"LB","flag":"https://flagcdn.com/w640/lb.png"},
  {"name":"Saint Lucia","officialName":"Saint Lucia","cca2":"LC","flag":"https://flagcdn.com/w640/lc.png"},
  {"name":"Liechtenstein","officialName":"Principality of Liechtenstein","cca2":"LI","flag":"https://flagcdn.com/w640/li.png"},
  {"name":"Sri Lanka","officialName":"Democratic Socialist Republic of Sri Lanka","cca2":"LK","flag":"https://flagcdn.com/w640/lk.png"},
  {"name":"Liberia","officialName":"Republic of Liberia","cca2":"LR","flag":"https://flagcdn.com/w640/lr.png"},
  {"name":"Lesotho","officialName":"Kingdom of Lesotho","cca2":"LS","flag":"https://flagcdn.com/w640/ls.png"},
  {"name":"Lithuania","officialName":"Republic of Lithuania","cca2":"LT","flag":"https://flagcdn.com/w640/lt.png"},
  {"name":"Luxembourg","officialName":"Grand Duchy of Luxembourg","cca2":"LU","flag":"https://flagcdn.com/w640/lu.png"},
  {"name":"Latvia","officialName":"Republic of Latvia","cca2":"LV","flag":"https://flagcdn.com/w640/lv.png"},
  {"name":"Libya","officialName":"State of Libya","cca2":"LY","flag":"https://flagcdn.com/w640/ly.png"},
  {"name":"Morocco","officialName":"Kingdom of Morocco","cca2":"MA","flag":"https://flagcdn.com/w640/ma.png"},
  {"name":"Monaco","officialName":"Principality of Monaco","cca2":"MC","flag":"https://flagcdn.com/w640/mc.png"},
  {"name":"Moldova","officialName":"Republic of Moldova","cca2":"MD","flag":"https://flagcdn.com/w640/md.png"},
  {"name":"Montenegro","officialName":"Montenegro","cca2":"ME","flag":"https://flagcdn.com/w640/me.png"},
  {"name":"Saint Martin","officialName":"Saint Martin","cca2":"MF","flag":"https://flagcdn.com/w640/mf.png"},
  {"name":"Madagascar","officialName":"Republic of Madagascar","cca2":"MG","flag":"https://flagcdn.com/w640/mg.png"},
  {"name":"Marshall Islands","officialName":"Republic of the Marshall Islands","cca2":"MH","flag":"https://flagcdn.com/w640/mh.png"},
  {"name":"North Macedonia","officialName":"Republic of North Macedonia","cca2":"MK","flag":"https://flagcdn.com/w640/mk.png"},
  {"name":"Mali","officialName":"Republic of Mali","cca2":"ML","flag":"https://flagcdn.com/w640/ml.png"},
  {"name":"Myanmar","officialName":"Republic of the Union of Myanmar","cca2":"MM","flag":"https://flagcdn.com/w640/mm.png"},
  {"name":"Mongolia","officialName":"Mongolia","cca2":"MN","flag":"https://flagcdn.com/w640/mn.png"},
  {"name":"Macao","officialName":"Macao Special Administrative Region of the People's Republic of China","cca2":"MO","flag":"https://flagcdn.com/w640/mo.png"},
  {"name":"Northern Mariana Islands","officialName":"Northern Mariana Islands","cca2":"MP","flag":"https://flagcdn.com/w640/mp.png"},
  {"name":"Martinique","officialName":"Martinique","cca2":"MQ","flag":"https://flagcdn.com/w640/mq.png"},
  {"name":"Mauritania","officialName":"Islamic Republic of Mauritania","cca2":"MR","flag":"https://flagcdn.com/w640/mr.png"},
  {"name":"Montserrat","officialName":"Montserrat","cca2":"MS","flag":"https://flagcdn.com/w640/ms.png"},
  {"name":"Malta","officialName":"Republic of Malta","cca2":"MT","flag":"https://flagcdn.com/w640/mt.png"},
  {"name":"Mauritius","officialName":"Republic of Mauritius","cca2":"MU","flag":"https://flagcdn.com/w640/mu.png"},
  {"name":"Maldives","officialName":"Republic of Maldives","cca2":"MV","flag":"https://flagcdn.com/w640/mv.png"},
  {"name":"Malawi","officialName":"Republic of Malawi","cca2":"MW","flag":"https://flagcdn.com/w640/mw.png"},
  {"name":"Mexico","officialName":"United Mexican States","cca2":"MX","flag":"https://flagcdn.com/w640/mx.png"},
  {"name":"Malaysia","officialName":"Malaysia","cca2":"MY","flag":"https://flagcdn.com/w640/my.png"},
  {"name":"Mozambique","officialName":"Republic of Mozambique","cca2":"MZ","flag":"https://flagcdn.com/w640/mz.png"},
  {"name":"Namibia","officialName":"Republic of Namibia","cca2":"NA","flag":"https://flagcdn.com/w640/na.png"},
  {"name":"New Caledonia","officialName":"New Caledonia","cca2":"NC","flag":"https://flagcdn.com/w640/nc.png"},
  {"name":"Niger","officialName":"Republic of the Niger","cca2":"NE","flag":"https://flagcdn.com/w640/ne.png"},
  {"name":"Norfolk Island","officialName":"Territory of Norfolk Island","cca2":"NF","flag":"https://flagcdn.com/w640/nf.png"},
  {"name":"Nigeria","officialName":"Federal Republic of Nigeria","cca2":"NG","flag":"https://flagcdn.com/w640/ng.png"},
  {"name":"Nicaragua","officialName":"Republic of Nicaragua","cca2":"NI","flag":"https://flagcdn.com/w640/ni.png"},
  {"name":"Netherlands","officialName":"Kingdom of the Netherlands","cca2":"NL","flag":"https://flagcdn.com/w640/nl.png"},
  {"name":"Norway","officialName":"Kingdom of Norway","cca2":"NO","flag":"https://flagcdn.com/w640/no.png"},
  {"name":"Nepal","officialName":"Federal Democratic Republic of Nepal","cca2":"NP","flag":"https://flagcdn.com/w640/np.png"},
  {"name":"Nauru","officialName":"Republic of Nauru","cca2":"NR","flag":"https://flagcdn.com/w640/nr.png"},
  {"name":"Niue","officialName":"Niue","cca2":"NU","flag":"https://flagcdn.com/w640/nu.png"},
  {"name":"New Zealand","officialName":"New Zealand","cca2":"NZ","flag":"https://flagcdn.com/w640/nz.png"},
  {"name":"Oman","officialName":"Sultanate of Oman","cca2":"OM","flag":"https://flagcdn.com/w640/om.png"},
  {"name":"Panama","officialName":"Republic of Panama","cca2":"PA","flag":"https://flagcdn.com/w640/pa.png"},
  {"name":"Peru","officialName":"Republic of Peru","cca2":"PE","flag":"https://flagcdn.com/w640/pe.png"},
  {"name":"French Polynesia","officialName":"French Polynesia","cca2":"PF","flag":"https://flagcdn.com/w640/pf.png"},
  {"name":"Papua New Guinea","officialName":"Independent State of Papua New Guinea","cca2":"PG","flag":"https://flagcdn.com/w640/pg.png"},
  {"name":"Philippines","officialName":"Republic of the Philippines","cca2":"PH","flag":"https://flagcdn.com/w640/ph.png"},
  {"name":"Pakistan","officialName":"Islamic Republic of Pakistan","cca2":"PK","flag":"https://flagcdn.com/w640/pk.png"},
  {"name":"Poland","officialName":"Republic of Poland","cca2":"PL","flag":"https://flagcdn.com/w640/pl.png"},
  {"name":"Saint Pierre and Miquelon","officialName":"Saint Pierre and Miquelon","cca2":"PM","flag":"https://flagcdn.com/w640/pm.png"},
  {"name":"Pitcairn","officialName":"Pitcairn Group of Islands","cca2":"PN","flag":"https://flagcdn.com/w640/pn.png"},
  {"name":"Puerto Rico","officialName":"Commonwealth of Puerto Rico","cca2":"PR","flag":"https://flagcdn.com/w640/pr.png"},
  {"name":"Palestine","officialName":"State of Palestine","cca2":"PS","flag":"https://flagcdn.com/w640/ps.png"},
  {"name":"Portugal","officialName":"Portuguese Republic","cca2":"PT","flag":"https://flagcdn.com/w640/pt.png"},
  {"name":"Palau","officialName":"Republic of Palau","cca2":"PW","flag":"https://flagcdn.com/w640/pw.png"},
  {"name":"Paraguay","officialName":"Republic of Paraguay","cca2":"PY","flag":"https://flagcdn.com/w640/py.png"},
  {"name":"Qatar","officialName":"State of Qatar","cca2":"QA","flag":"https://flagcdn.com/w640/qa.png"},
  {"name":"Réunion","officialName":"Réunion Island","cca2":"RE","flag":"https://flagcdn.com/w640/re.png"},
  {"name":"Romania","officialName":"Romania","cca2":"RO","flag":"https://flagcdn.com/w640/ro.png"},
  {"name":"Serbia","officialName":"Republic of Serbia","cca2":"RS","flag":"https://flagcdn.com/w640/rs.png"},
  {"name":"Russia","officialName":"Russian Federation","cca2":"RU","flag":"https://flagcdn.com/w640/ru.png"},
  {"name":"Rwanda","officialName":"Republic of Rwanda","cca2":"RW","flag":"https://flagcdn.com/w640/rw.png"},
  {"name":"Saudi Arabia","officialName":"Kingdom of Saudi Arabia","cca2":"SA","flag":"https://flagcdn.com/w640/sa.png"},
  {"name":"Solomon Islands","officialName":"Solomon Islands","cca2":"SB","flag":"https://flagcdn.com/w640/sb.png"},
  {"name":"Seychelles","officialName":"Republic of Seychelles","cca2":"SC","flag":"https://flagcdn.com/w640/sc.png"},
  {"name":"Sudan","officialName":"Republic of the Sudan","cca2":"SD","flag":"https://flagcdn.com/w640/sd.png"},
  {"name":"Sweden","officialName":"Kingdom of Sweden","cca2":"SE","flag":"https://flagcdn.com/w640/se.png"},
  {"name":"Singapore","officialName":"Republic of Singapore","cca2":"SG","flag":"https://flagcdn.com/w640/sg.png"},
  {"name":"Saint Helena, Ascension and Tristan da Cunha","officialName":"Saint Helena, Ascension and Tristan da Cunha","cca2":"SH","flag":"https://flagcdn.com/w640/sh.png"},
  {"name":"Slovenia","officialName":"Republic of Slovenia","cca2":"SI","flag":"https://flagcdn.com/w640/si.png"},
  {"name":"Svalbard and Jan Mayen","officialName":"Svalbard og Jan Mayen","cca2":"SJ","flag":"https://flagcdn.com/w640/sj.png"},
  {"name":"Slovakia","officialName":"Slovak Republic","cca2":"SK","flag":"https://flagcdn.com/w640/sk.png"},
  {"name":"Sierra Leone","officialName":"Republic of Sierra Leone","cca2":"SL","flag":"https://flagcdn.com/w640/sl.png"},
  {"name":"San Marino","officialName":"Republic of San Marino","cca2":"SM","flag":"https://flagcdn.com/w640/sm.png"},
  {"name":"Senegal","officialName":"Republic of Senegal","cca2":"SN","flag":"https://flagcdn.com/w640/sn.png"},
  {"name":"Somalia","officialName":"Federal Republic of Somalia","cca2":"SO","flag":"https://flagcdn.com/w640/so.png"},
  {"name":"Suriname","officialName":"Republic of Suriname","cca2":"SR","flag":"https://flagcdn.com/w640/sr.png"},
  {"name":"South Sudan","officialName":"Republic of South Sudan","cca2":"SS","flag":"https://flagcdn.com/w640/ss.png"},
  {"name":"Sao Tome and Principe","officialName":"Democratic Republic of Sao Tome and Principe","cca2":"ST","flag":"https://flagcdn.com/w640/st.png"},
  {"name":"El Salvador","officialName":"Republic of El Salvador","cca2":"SV","flag":"https://flagcdn.com/w640/sv.png"},
  {"name":"Sint Maarten","officialName":"Sint Maarten","cca2":"SX","flag":"https://flagcdn.com/w640/sx.png"},
  {"name":"Syria","officialName":"Syrian Arab Republic","cca2":"SY","flag":"https://flagcdn.com/w640/sy.png"},
  {"name":"Eswatini","officialName":"Kingdom of Eswatini","cca2":"SZ","flag":"https://flagcdn.com/w640/sz.png"},
  {"name":"Turks and Caicos Islands","officialName":"Turks and Caicos Islands","cca2":"TC","flag":"https://flagcdn.com/w640/tc.png"},
  {"name":"Chad","officialName":"Republic of Chad","cca2":"TD","flag":"https://flagcdn.com/w640/td.png"},
  {"name":"French Southern Territories","officialName":"Territory of the French Southern and Antarctic Lands","cca2":"TF","flag":"https://flagcdn.com/w640/tf.png"},
  {"name":"Togo","officialName":"Togolese Republic","cca2":"TG","flag":"https://flagcdn.com/w640/tg.png"},
  {"name":"Thailand","officialName":"Kingdom of Thailand","cca2":"TH","flag":"https://flagcdn.com/w640/th.png"},
  {"name":"Tajikistan","officialName":"Republic of Tajikistan","cca2":"TJ","flag":"https://flagcdn.com/w640/tj.png"},
  {"name":"Tokelau","officialName":"Tokelau","cca2":"TK","flag":"https://flagcdn.com/w640/tk.png"},
  {"name":"Turkmenistan","officialName":"Turkmenistan","cca2":"TM","flag":"https://flagcdn.com/w640/tm.png"},
  {"name":"Timor-Leste","officialName":"Democratic Republic of Timor-Leste","cca2":"TL","flag":"https://flagcdn.com/w640/tl.png"},
  {"name":"Tonga","officialName":"Kingdom of Tonga","cca2":"TO","flag":"https://flagcdn.com/w640/to.png"},
  {"name":"Trinidad and Tobago","officialName":"Republic of Trinidad and Tobago","cca2":"TT","flag":"https://flagcdn.com/w640/tt.png"},
  {"name":"Tunisia","officialName":"Tunisian Republic","cca2":"TN","flag":"https://flagcdn.com/w640/tn.png"},
  {"name":"Türkiye","officialName":"Republic of Türkiye","cca2":"TR","flag":"https://flagcdn.com/w640/tr.png"},
  {"name":"Tuvalu","officialName":"Tuvalu","cca2":"TV","flag":"https://flagcdn.com/w640/tv.png"},
  {"name":"Taiwan","officialName":"Republic of China","cca2":"TW","flag":"https://flagcdn.com/w640/tw.png"},
  {"name":"Tanzania","officialName":"United Republic of Tanzania","cca2":"TZ","flag":"https://flagcdn.com/w640/tz.png"},
  {"name":"Ukraine","officialName":"Ukraine","cca2":"UA","flag":"https://flagcdn.com/w640/ua.png"},
  {"name":"Uganda","officialName":"Republic of Uganda","cca2":"UG","flag":"https://flagcdn.com/w640/ug.png"},
  {"name":"United States Minor Outlying Islands","officialName":"United States Minor Outlying Islands","cca2":"UM","flag":"https://flagcdn.com/w640/um.png"},
  {"name":"United States","officialName":"United States of America","cca2":"US","flag":"https://flagcdn.com/w640/us.png"},
  {"name":"Uruguay","officialName":"Oriental Republic of Uruguay","cca2":"UY","flag":"https://flagcdn.com/w640/uy.png"},
  {"name":"Uzbekistan","officialName":"Republic of Uzbekistan","cca2":"UZ","flag":"https://flagcdn.com/w640/uz.png"},
  {"name":"Vatican City","officialName":"Vatican City State","cca2":"VA","flag":"https://flagcdn.com/w640/va.png"},
  {"name":"Saint Vincent and the Grenadines","officialName":"Saint Vincent and the Grenadines","cca2":"VC","flag":"https://flagcdn.com/w640/vc.png"},
  {"name":"Venezuela","officialName":"Bolivarian Republic of Venezuela","cca2":"VE","flag":"https://flagcdn.com/w640/ve.png"},
  {"name":"British Virgin Islands","officialName":"Virgin Islands","cca2":"VG","flag":"https://flagcdn.com/w640/vg.png"},
  {"name":"United States Virgin Islands","officialName":"Virgin Islands of the United States","cca2":"VI","flag":"https://flagcdn.com/w640/vi.png"},
  {"name":"Vietnam","officialName":"Socialist Republic of Viet Nam","cca2":"VN","flag":"https://flagcdn.com/w640/vn.png"},
  {"name":"Vanuatu","officialName":"Republic of Vanuatu","cca2":"VU","flag":"https://flagcdn.com/w640/vu.png"},
  {"name":"Wallis and Futuna","officialName":"Territory of the Wallis and Futuna Islands","cca2":"WF","flag":"https://flagcdn.com/w640/wf.png"},
  {"name":"Samoa","officialName":"Independent State of Samoa","cca2":"WS","flag":"https://flagcdn.com/w640/ws.png"},
  {"name":"Kosovo","officialName":"Republic of Kosovo","cca2":"XK","flag":"https://flagcdn.com/w640/xk.png"},
  {"name":"Yemen","officialName":"Republic of Yemen","cca2":"YE","flag":"https://flagcdn.com/w640/ye.png"},
  {"name":"Mayotte","officialName":"Department of Mayotte","cca2":"YT","flag":"https://flagcdn.com/w640/yt.png"},
  {"name":"South Africa","officialName":"Republic of South Africa","cca2":"ZA","flag":"https://flagcdn.com/w640/za.png"},
  {"name":"Zambia","officialName":"Republic of Zambia","cca2":"ZM","flag":"https://flagcdn.com/w640/zm.png"},
  {"name":"Zimbabwe","officialName":"Republic of Zimbabwe","cca2":"ZW","flag":"https://flagcdn.com/w640/zw.png"}
];
